### ISSUE TITLE
Consider using Phoronix Test Suite

### ISSUE THREAD

**Issue by lnicola** [pid1/test-sec-flags#11] opened 2016-07-18 10:14 UTC
It might be a good idea to use PTS to measure the overall impact of changes after rebuilding the whole system.

**Comment by anthraxx** [comment] 2016-07-18 10:24
i think that's out of scope of this project, the main focus of this is to bring up relative numbers and there is no way to rebuild the whole system and jump between those states. I don't see where adding PTS here would make any sense

**Comment by lnicola** [comment] 2016-07-18 12:07
You're right that it would be outside the scope of this GitHub project, but the project goal is "to determine if these flags can be the new default for all Arch Linux packages". The applications tested here consist of tight loops. I would argue that the results would not generalize well to a complete distribution compiled with the new flags.

AFAIK, Intel's Clear Linux project uses more aggressive optimization settings for its packages and [it seems to work pretty well](https://www.phoronix.com/scan.php?page=article&item=10-way-2016). Conversely, I would argue that enabling more checks will have a similar negative performance. I also don't think that the tests here can prove that it's a good idea to enable them for every package offered by Arch Linux.

**Comment by anthraxx** [comment] 2016-07-18 12:40
in fact why not, they prove what they are supposed to prove, the relative impact of each of the combination of flags.
Fedora and other distributions already went this way and enabled the full set of flags for security. Also the current results show that we already have the most expensive one in place: stack-protector-strong. Compared to that its mostly like a NOOP, if the argument is to get any fraction of pseudo performance then we should go away from virtual memory addressing and use static hardware addressed memory: its faster

**Comment by lnicola** [comment] 2016-07-18 13:18
I'm not arguing for another operating system or hardware architecture, so please don't be snarky. My concern is that the results obtained here do not generalize well to more complex applications like web browsers or compilers.

`xz` and `ffmpeg` have tight loops [1] that probably fit in the instruction cache, while `UnixBench` tests arithmetic and system call/IPC overhead (which is not affected by compiler options). EDIT: Perhaps `-fno-plt` helps, but `PIE` has been shown to have a detrimental performance impact [2].

If the discussion was about making things faster I would argue for enabling LTO for some packages, like Clear Linux does, but it is not. I only hope that the decision to introduce more run-time checks will not be motivated by tests that don't exercise them.

EDIT:
[1] running tight loops reduces the impact of e.g. stack checks.
[2] https://access.redhat.com/blogs/766093/posts/1975803

**Comment by pid1** [comment] 2016-07-18 13:24
@lnicola Patches welcome.

**Comment by anthraxx** [comment] 2016-07-18 13:24
instruction cache is one thing, yes. however those flags affect anything that uses functions and library calls as (besides pie) we are also speaking about stack-check and no-plt options that indeed affect all those programs in one or the other way.

**Comment by pid1** [comment] 2016-08-02 12:36
I'm going to close this as this is a feature request, not a bug. If someone wants to start pushing commits, we can coordinate in #archlinux-security.

**Closed as completed by pid1** 2016-08-02 12:36 UTC

**Comment by pid1** [comment] 2016-08-02 12:45
Added to https://github.com/pid1/test-sec-flags/wiki/Feature-Requests
